version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nft_marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # Optional web UI
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:

